/**
 * Verified ERC20 token presets for Starknet mainnet.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx scripts/generate-token-presets.ts --network mainnet
 * Source: AVNU API (https://starknet.api.avnu.fi)
 */

import type { Token, Address } from "@/types";

export const mainnetTokens = {
  USDC: {
    name: "USDC",
    address:
      "0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb" as Address,
    decimals: 6,
    symbol: "USDC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png"
      ),
    },
  },
  ETH: {
    name: "Ethereum",
    address:
      "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7" as Address,
    decimals: 18,
    symbol: "ETH",
    metadata: {
      logoUrl: new URL(
        "https://imagedelivery.net/0xPAQaDtnQhBs8IzYRIlNg/e07829b7-0382-4e03-7ecd-a478c5aa9f00/logo"
      ),
    },
  },
  WBTC: {
    name: "Wrapped BTC",
    address:
      "0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac" as Address,
    decimals: 8,
    symbol: "WBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599/logo.png"
      ),
    },
  },
  STRK: {
    name: "Starknet",
    address:
      "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d" as Address,
    decimals: 18,
    symbol: "STRK",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/26433/small/starknet.png"
      ),
    },
  },
  USDC_E: {
    name: "Bridged USDC",
    address:
      "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8" as Address,
    decimals: 6,
    symbol: "USDC.e",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png"
      ),
    },
  },
  USDT: {
    name: "Tether USD",
    address:
      "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8" as Address,
    decimals: 6,
    symbol: "USDT",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/325/small/Tether.png"
      ),
    },
  },
  TBTC: {
    name: "Starknet tBTC",
    address:
      "0x04daa17763b286d1e59b97c283c0b8c949994c361e426a28f743c67bdfe9a32f" as Address,
    decimals: 18,
    symbol: "tBTC",
    metadata: {
      logoUrl: new URL(
        "https://pbs.twimg.com/profile_images/1822041772576460801/LEJSjZWK_400x400.jpg"
      ),
    },
  },
  CASH: {
    name: "Cash",
    address:
      "0x0498edfaf50ca5855666a700c25dd629d577eb9afccdf3b5977aec79aee55ada" as Address,
    decimals: 18,
    symbol: "CASH",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/lindy-labs/opus_contracts/refs/heads/main/assets/CASH_no_margin_1x.png"
      ),
    },
  },
  DAI: {
    name: "Dai Stablecoin",
    address:
      "0x05574eb6b8789a91466f902c380d978e472db68170ff82a5b650b95a58ddf4ad" as Address,
    decimals: 18,
    symbol: "DAI",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png"
      ),
    },
  },
  USN: {
    name: "USN",
    address:
      "0x01e6545cab7ba4ac866768ba5e1bd540893762286ed3fea7f9c02bfa147e135b" as Address,
    decimals: 18,
    symbol: "USN",
    metadata: {
      logoUrl: new URL(
        "https://storage.googleapis.com/prod-pendle-bucket-a/images/uploads/31cf1a6e-1b01-4db8-abf6-e52651b1fd05.svg"
      ),
    },
  },
  LBTC: {
    name: "Lombard Staked Bitcoin",
    address:
      "0x036834a40984312f7f7de8d31e3f6305b325389eaeea5b1c0664b2fb936461a4" as Address,
    decimals: 8,
    symbol: "LBTC",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/39969/standard/LBTC_Logo.png"
      ),
    },
  },
  WSTETH: {
    name: "Wrapped Staked Ether",
    address:
      "0x0057912720381af14b0e5c87aa4718ed5e527eab60b3801ebf702ab09139e38b" as Address,
    decimals: 18,
    symbol: "wstETH",
    metadata: {
      logoUrl: new URL(
        "https://static.starkscan.co/tokens/0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2/icons/QmaxTVxd6ZWrotuG64LiuL8PCEgwjiHiQF9isCu8QKgneP"
      ),
    },
  },
  SUSN: {
    name: "Staked USN",
    address:
      "0x02411565ef1a14decfbe83d2e987cced918cd752508a3d9c55deb67148d14d17" as Address,
    decimals: 18,
    symbol: "sUSN",
    metadata: {
      logoUrl: new URL(
        "https://storage.googleapis.com/prod-pendle-bucket-a/images/uploads/dc424e27-4538-4126-8df6-eb7b432853bf.svg"
      ),
    },
  },
  XSTRK: {
    name: "Endur xSTRK",
    address:
      "0x028d709c875c0ceac3dce7065bec5328186dc89fe254527084d1689910954b0a" as Address,
    decimals: 18,
    symbol: "xSTRK",
    metadata: {
      logoUrl: new URL("https://dashboard.endur.fi/endur-fi.svg"),
    },
  },
  XWBTC: {
    name: "Endur xWBTC",
    address:
      "0x06a567e68c805323525fe1649adb80b03cddf92c23d2629a6779f54192dffc13" as Address,
    decimals: 8,
    symbol: "xWBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/avnu-labs/tokens/refs/heads/main/images/xWBTC.svg"
      ),
    },
  },
  DAIV0: {
    name: "Dai Stablecoin V0",
    address:
      "0x00da114221cb83fa859dbdb4c44beeaa0bb37c7537ad5ae66fe5e0efd20e6eb3" as Address,
    decimals: 18,
    symbol: "DAIv0",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png"
      ),
    },
  },
  EKUBO: {
    name: "Ekubo Protocol",
    address:
      "0x075afe6402ad5a5c20dd25e10ec3b3986acaa647b77e4ae24b0cbc9a54a27a87" as Address,
    decimals: 18,
    symbol: "EKUBO",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/37715/standard/135474885.png"
      ),
    },
  },
  WSTETH_LEGACY: {
    name: "Legacy Starknet Wrapped Staked Ether",
    address:
      "0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2" as Address,
    decimals: 18,
    symbol: "wstETH(legacy)",
    metadata: {
      logoUrl: new URL(
        "https://wstethmigration.starknet.io/wsteth-legacy-icon.svg"
      ),
    },
  },
  LORDS: {
    name: "Lords",
    address:
      "0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49" as Address,
    decimals: 18,
    symbol: "LORDS",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/22171/small/Frame_1.png"
      ),
    },
  },
  NSTR: {
    name: "Nostra",
    address:
      "0x00c530f2c0aa4c16a0806365b0898499fba372e5df7a7172dc6fe9ba777e8007" as Address,
    decimals: 18,
    symbol: "NSTR",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/28282/small/Nostra_200x200.png"
      ),
    },
  },
  SOLVBTC: {
    name: "Solv BTC",
    address:
      "0x0593e034dda23eea82d2ba9a30960ed42cf4a01502cc2351dc9b9881f9931a68" as Address,
    decimals: 18,
    symbol: "SolvBTC",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/36800/standard/solvBTC.png"
      ),
    },
  },
  SURVIVOR: {
    name: "Survivor",
    address:
      "0x042dd777885ad2c116be96d4d634abc90a26a790ffb5871e037dd5ae7d2ec86b" as Address,
    decimals: 18,
    symbol: "SURVIVOR",
    metadata: {
      logoUrl: new URL("https://lootsurvivor.io/images/survivor_token.png"),
    },
  },
  USDU: {
    name: "Uncap USD",
    address:
      "0x02f94539f80158f9a48a7acf3747718dfbec9b6f639e2742c1fb44ae7ab5aa04" as Address,
    decimals: 18,
    symbol: "USDU",
    metadata: {
      logoUrl: new URL("https://uncap.finance/usdu.png"),
    },
  },
  DREAMS: {
    name: "Daydreams",
    address:
      "0x04fcaf2a7b4a072fe57c59beee807322d34ed65000d78611c909a46fead07fb1" as Address,
    decimals: 6,
    symbol: "dreams",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/53838/standard/ddpfp.png"
      ),
    },
  },
  DOG: {
    name: "DOG GO TO THE MOON",
    address:
      "0x040e81cfeb176bfdbc5047bbc55eb471cfab20a6b221f38d8fda134e1bfffca4" as Address,
    decimals: 5,
    symbol: "DOG",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/37352/standard/DOGGOTOTHEMOON.png"
      ),
    },
  },
  MRE7BTC: {
    name: "Midas Re7 BTC",
    address:
      "0x04e4fb1a9ca7e84bae609b9dc0078ad7719e49187ae7e425bb47d131710eddac" as Address,
    decimals: 18,
    symbol: "mRe7BTC",
    metadata: {
      logoUrl: new URL(
        "https://imagedelivery.net/0xPAQaDtnQhBs8IzYRIlNg/3a62ecee-1e58-45d3-9862-3ce90dff1900/logo"
      ),
    },
  },
  BROTHER: {
    name: "STARKNET BROTHER",
    address:
      "0x03b405a98c9e795d427fe82cdeeeed803f221b52471e3a757574a2b4180793ee" as Address,
    decimals: 18,
    symbol: "BROTHER",
    metadata: {
      logoUrl: new URL("https://i.imgur.com/mSywi47.png"),
    },
  },
  LUSD: {
    name: "LUSD Stablecoin",
    address:
      "0x070a76fd48ca0ef910631754d77dd822147fe98a569b826ec85e3c33fde586ac" as Address,
    decimals: 18,
    symbol: "LUSD",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/14666/small/Group_3.png"
      ),
    },
  },
  SCHIZODIO: {
    name: "SCHIZODIO",
    address:
      "0x00acc2fa3bb7f6a6726c14d9e142d51fe3984dbfa32b5907e1e76425177875e2" as Address,
    decimals: 18,
    symbol: "SCHIZODIO",
    metadata: {
      logoUrl: new URL("https://i.postimg.cc/25WRJg4t/Schizo-Face28.png"),
    },
  },
  BURR: {
    name: "Burrow",
    address:
      "0x01bc7c8ce3b8fe74e4870adc2965df850d429048e83fad93f3140f52ecb74add" as Address,
    decimals: 18,
    symbol: "BURR",
    metadata: {
      logoUrl: new URL(
        "https://bafybeibxu7laz6irmvjmb73hzue5yrgh4jytefxkskiifj7es7chasherq.ipfs.w3s.link/BURR%20logo.png"
      ),
    },
  },
  SOL: {
    name: "Solana",
    address:
      "0x01e70aedffd376afe33cebdf51ed5365131dccb2a5b2cb36d02b785442912b9b" as Address,
    decimals: 9,
    symbol: "SOL",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/4128/standard/solana.png"
      ),
    },
  },
  SLAY: {
    name: "Brother Eli",
    address:
      "0x02ab526354a39e7f5d272f327fa94e757df3688188d4a92c6dc3623ab79894e2" as Address,
    decimals: 18,
    symbol: "SLAY",
    metadata: {
      logoUrl: new URL("https://www.brothereli.com/logo.svg"),
    },
  },
  XTBTC: {
    name: "Endur xtBTC",
    address:
      "0x043a35c1425a0125ef8c171f1a75c6f31ef8648edcc8324b55ce1917db3f9b91" as Address,
    decimals: 18,
    symbol: "xtBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/avnu-labs/tokens/refs/heads/main/images/xtBTC.svg"
      ),
    },
  },
  XLBTC: {
    name: "Endur xLBTC",
    address:
      "0x07dd3c80de9fcc5545f0cb83678826819c79619ed7992cc06ff81fc67cd2efe0" as Address,
    decimals: 8,
    symbol: "xLBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/avnu-labs/tokens/refs/heads/main/images/xLBTC.svg"
      ),
    },
  },
  POL: {
    name: "Polygon",
    address:
      "0x02650ea9af204ba33d4e743ee8ff826b5bec3f5ce497efed832e5c3794483e3c" as Address,
    decimals: 18,
    symbol: "POL",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/32440/standard/polygon.png"
      ),
    },
  },
  UNI: {
    name: "Uniswap",
    address:
      "0x049210ffc442172463f3177147c1aeaa36c51d152c1b0630f2364c300d4f48ee" as Address,
    decimals: 18,
    symbol: "UNI",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984/logo.png"
      ),
    },
  },
  SWAY: {
    name: "Standard Weighted Adalian Yield",
    address:
      "0x004878d1148318a31829523ee9c6a5ee563af6cd87f90a30809e5b0d27db8a9b" as Address,
    decimals: 6,
    symbol: "SWAY",
    metadata: {
      logoUrl: new URL(
        "https://etherscan.io/token/images/influencesway_32.png"
      ),
    },
  },
  RETH: {
    name: "Rocket Pool ETH",
    address:
      "0x0319111a5037cbec2b3e638cc34a3474e2d2608299f3e62866e9cc683208c610" as Address,
    decimals: 18,
    symbol: "rETH",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/20764/large/reth.png"
      ),
    },
  },
  SSTR: {
    name: "SISTER",
    address:
      "0x0102d5e124c51b936ee87302e0f938165aec96fb6c2027ae7f3a5ed46c77573b" as Address,
    decimals: 18,
    symbol: "SSTR",
    metadata: {
      logoUrl: new URL(
        "https://res.cloudinary.com/dikavhrql/image/upload/v1732475722/pp-twitter-sstr_t2hd5h.png"
      ),
    },
  },
  SSTRK: {
    name: "Staked Starknet Token",
    address:
      "0x0356f304b154d29d2a8fe22f1cb9107a9b564a733cf6b4cc47fd121ac1af90c9" as Address,
    decimals: 18,
    symbol: "sSTRK",
    metadata: {
      logoUrl: new URL(
        "https://nimbora-assets.s3.eu-central-1.amazonaws.com/yieldTokens/Group+41.svg"
      ),
    },
  },
  PAL: {
    name: "Pain au lait",
    address:
      "0x049201f03a0f0a9e70e28dcd74cbf44931174dbe3cc4b2ff488898339959e559" as Address,
    decimals: 18,
    symbol: "PAL",
    metadata: {
      logoUrl: new URL(
        "https://pbs.twimg.com/profile_images/1761144682808025088/Ki19VFca_400x400.jpg"
      ),
    },
  },
  AAVE: {
    name: "Aave Token",
    address:
      "0x02f5eb9a4f77b6c7c83488418e77329d31eb43219745959948a0fce9580905d9" as Address,
    decimals: 18,
    symbol: "AAVE",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/12645/standard/aave-token-round.png?1720472354"
      ),
    },
  },
  ARB: {
    name: "Arbitrum",
    address:
      "0x03070d5cbd310edc0b2cfe8b11d132e67718b16c7fbfd536ee74ec54a4307ba2" as Address,
    decimals: 18,
    symbol: "ARB",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/16547/standard/arb.jpg"
      ),
    },
  },
  AUSD0: {
    name: "AUSD0",
    address:
      "0x04887629c229b4ee8e82f3db4cddeb1b2c0f084d46f229672623bd1282df5931" as Address,
    decimals: 6,
    symbol: "AUSD0",
    metadata: {
      logoUrl: new URL(
        "https://gist.githubusercontent.com/vanderspuy/1d6a1d852ec40bedc61c65c0a6caef9d/raw/736946a5434d2a625b00f988bcf44b171152fd9a/ausd0.svg"
      ),
    },
  },
  BONK: {
    name: "Bonk",
    address:
      "0x074238dfa02063792077820584c925b679a013cbab38e5ca61af5627d1eda736" as Address,
    decimals: 5,
    symbol: "BONK",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/28600/standard/bonk.jpg"
      ),
    },
  },
  DTICKET: {
    name: "Dungeon Ticket",
    address:
      "0x0452810188c4cb3aebd63711a3b445755bc0d6c4f27b923fdd99b1a118858136" as Address,
    decimals: 18,
    symbol: "DTICKET",
    metadata: {
      logoUrl: new URL("https://lootsurvivor.io/images/dungeon_ticket.png"),
    },
  },
  XSBTC: {
    name: "Endur xsBTC",
    address:
      "0x0580f3dc564a7b82f21d40d404b3842d490ae7205e6ac07b1b7af2b4a5183dc9" as Address,
    decimals: 18,
    symbol: "xsBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/avnu-labs/tokens/refs/heads/main/images/xsBTC.svg"
      ),
    },
  },
  ENA: {
    name: "Ethena",
    address:
      "0x019110887221c1cb3fa95bbbfce818c88bfd6a74af2c4574b6455dd1bdc9a974" as Address,
    decimals: 18,
    symbol: "ENA",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/36530/standard/ethena.png"
      ),
    },
  },
  FARTCOIN: {
    name: "Fartcoin",
    address:
      "0x06e0e0117b742747452601f9f14576eb9d71b326379a1794bb51d9adbce3dbd3" as Address,
    decimals: 6,
    symbol: "Fartcoin",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/50891/standard/fart.jpg"
      ),
    },
  },
  FYWBTC: {
    name: "ForgeYieldsWBTC",
    address:
      "0x04dd39de0a588f5e1c7a8377e1bef2c49caaee49a11433429d2c48f587b3a492" as Address,
    decimals: 8,
    symbol: "fyWBTC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/ForgeYields/forgeyields-logo/refs/heads/main/png/fywbtc_dark.png"
      ),
    },
  },
  JUP: {
    name: "Jupiter",
    address:
      "0x03a292bd498266ac4b05d93cc2df5cd7883c0684faabff182ab568d566a3c151" as Address,
    decimals: 6,
    symbol: "JUP",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/34188/standard/jup.png"
      ),
    },
  },
  KSTRK: {
    name: "kSTRK Token",
    address:
      "0x045cd05ee2caaac3459b87e5e2480099d201be2f62243f839f00e10dde7f500c" as Address,
    decimals: 18,
    symbol: "kSTRK",
    metadata: {
      logoUrl: new URL("https://app.zklend.com/icons/tokens/kstrk.svg"),
    },
  },
  ZRO: {
    name: "LayerZero",
    address:
      "0x01e77aec81ef65db5fb788a5a04fd9d23f6f4c860eb2fb0e99ace5c45b021071" as Address,
    decimals: 18,
    symbol: "ZRO",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/28206/standard/ftxG9_TJ_400x400.jpeg"
      ),
    },
  },
  MRE7YIELD: {
    name: "Midas Re7 Yield",
    address:
      "0x04be8945e61dc3e19ebadd1579a6bd53b262f51ba89e6f8b0c4bc9a7e3c633fc" as Address,
    decimals: 18,
    symbol: "mRe7YIELD",
    metadata: {
      logoUrl: new URL("https://midas.app/assets/mre7-BcOOHm7i.svg"),
    },
  },
  TRUMP: {
    name: "Official Trump",
    address:
      "0x07380caa64fdf27501afad0bd93c89d1e83a081a553af89bbeffb28dae8d8916" as Address,
    decimals: 6,
    symbol: "TRUMP",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/53746/standard/trump.png"
      ),
    },
  },
  SHIB: {
    name: "Shiba Inu",
    address:
      "0x02119755fad7cbf637d80cae5d3e8e12487befe6653ddd04432a73f6f569f46b" as Address,
    decimals: 18,
    symbol: "SHIB",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/11939/standard/shiba.png"
      ),
    },
  },
  VSTRK: {
    name: "Starknet Voting Token",
    address:
      "0x0782f0ddca11d9950bc3220e35ac82cf868778edb67a5e58b39838544bc4cd0f" as Address,
    decimals: 18,
    symbol: "vSTRK",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/26433/small/starknet.png"
      ),
    },
  },
  _1CHAIN: {
    name: "1CHAIN",
    address:
      "0x013833e26d675e3254186688ce764c99c43089f65e37afeefee6aed3953ed550" as Address,
    decimals: 18,
    symbol: "1CHAIN",
    metadata: {
      logoUrl: new URL(
        "https://ik.imagekit.io/ikof/photo_2025-05-27_20-34-05.jpg"
      ),
    },
  },
  ALF: {
    name: "Alf the Alpha",
    address:
      "0x078d7dfcddb44667153513bd837ff534ef395484f4b6cf28faa25b2c46e063d9" as Address,
    decimals: 18,
    symbol: "ALF",
    metadata: {
      logoUrl: new URL(
        "https://dd.dexscreener.com/ds-data/tokens/starknet/0x078d7dfcddb44667153513bd837ff534ef395484f4b6cf28faa25b2c46e063d9.png"
      ),
    },
  },
  DICK: {
    name: "DICK",
    address:
      "0x0388588584bd8c651151f6baf241a85827e7ff0574101f2a8194a3df68a7e2fe" as Address,
    decimals: 18,
    symbol: "DICK",
    metadata: {
      logoUrl: new URL(
        "https://pbs.twimg.com/profile_images/1853796021572104193/HVtV-qa6_400x400.jpg"
      ),
    },
  },
  DOSIS: {
    name: "dosis.fun",
    address:
      "0x04cd1aebaeebed861072e715bc8963d6cd39b73aba0d563b03d7e8f008e09bdb" as Address,
    decimals: 18,
    symbol: "DOSIS",
    metadata: {
      logoUrl: new URL(
        "https://www.dosis.fun/favicon.ico?favicon.136bf90e.ico"
      ),
    },
  },
  ESCARGOT: {
    name: "Escargot",
    address:
      "0x077779fbdcae5c2b4c321d336f2ccf80c2dd0ada63215901508f63e0b261df60" as Address,
    decimals: 18,
    symbol: "Escargot",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/BarryTaylor7/Escargot-token/main/Escargot.png"
      ),
    },
  },
  BLOCK: {
    name: "Focus on my Block",
    address:
      "0x0479713d106894923ec7d57a81dadc4b6d43e4272dced78d961ebe209669847c" as Address,
    decimals: 18,
    symbol: "BLOCK",
    metadata: {
      logoUrl: new URL(
        "https://ik.imagekit.io/ikof/8f27edb0-1079-46c3-b3ea-265c5071df60.png?updatedAt=1747996059352"
      ),
    },
  },
  GRINTA: {
    name: "GRINTA",
    address:
      "0x04448bec5fa63f320ef14531ffa9fe75618fec36e72b5072de59279a3f5473ad" as Address,
    decimals: 18,
    symbol: "GRINTA",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/avnu-labs/tokens/refs/heads/main/images/GwMhELJWsAArhsB.jpeg"
      ),
    },
  },
  SLINK: {
    name: "Slinky",
    address:
      "0x013ff4e86fa3e7286cc5c64b62f4099cf41e7918d727d22a5109ecfd00274d19" as Address,
    decimals: 18,
    symbol: "SLINK",
    metadata: {
      logoUrl: new URL(
        "https://ik.imagekit.io/lens/media-snapshot/29fe9c3ec925afa1c89c96fe3221353647578d3cb967d03fe9e6773ebd616af7.jpg"
      ),
    },
  },
  TWC: {
    name: "TrumpWifCat",
    address:
      "0x0768aef7aea42030cb701e1a97984b8f91b8f306a34bd0d461c466012d720b4b" as Address,
    decimals: 18,
    symbol: "TWC",
    metadata: {
      logoUrl: new URL("https://i.ibb.co/fr8Sh0Y/trumpwifcatlogo.png"),
    },
  },
  WIZ: {
    name: "wizardwifhat",
    address:
      "0x006e987f1e703c549991e1c13b8f1b8e1e6f8bba068a0715b9aacb51dba2800f" as Address,
    decimals: 18,
    symbol: "WIZ",
    metadata: {
      logoUrl: new URL(
        "https://pbs.twimg.com/profile_images/1844906927832145920/oX9_I7Oc_400x400.jpg"
      ),
    },
  },
  AKU: {
    name: "Akamaru",
    address:
      "0x0137dfca7d96cdd526d13a63176454f35c691f55837497448fad352643cfe4d4" as Address,
    decimals: 18,
    symbol: "AKU",
    metadata: {
      logoUrl: new URL("https://www.akamarutoken.com/logo.png"),
    },
  },
  FYETH: {
    name: "ForgeYieldsETH",
    address:
      "0x050707bc3b8730022f10530c2c6f6b9467644129c50c2868ad0036c5e4e9e616" as Address,
    decimals: 18,
    symbol: "fyETH",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/ForgeYields/forgeyields-logo/refs/heads/main/png/fyeth_dark.png"
      ),
    },
  },
  FYUSDC: {
    name: "ForgeYieldsUSDC",
    address:
      "0x07fdcec0cef01294c9c3d52415215949805c77bae8003702a7928fd6d2c36bc1" as Address,
    decimals: 6,
    symbol: "fyUSDC",
    metadata: {
      logoUrl: new URL(
        "https://raw.githubusercontent.com/ForgeYields/forgeyields-logo/refs/heads/main/png/fyusdc_dark.png"
      ),
    },
  },
  RUSDC_STARK: {
    name: "Relend Network USDC - Starknet",
    address:
      "0x02019e47a0bc54ea6b4853c6123ffc8158ea3ae2af4166928b0de6e89f06de6c" as Address,
    decimals: 6,
    symbol: "rUSDC-stark",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/55061/standard/rUSDC-_200x200.png"
      ),
    },
  },
  UNO: {
    name: "UNO",
    address:
      "0x0719b5092403233201aa822ce928bd4b551d0cdb071a724edd7dc5e5f57b7f34" as Address,
    decimals: 18,
    symbol: "UNO",
    metadata: {
      logoUrl: new URL(
        "https://assets.coingecko.com/coins/images/28283/standard/UNO.png?1710957910"
      ),
    },
  },
} as const satisfies Record<string, Token>;
