/**
 * Staking validator presets for Starknet sepolia.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx scripts/generate-validator-presets.ts --network sepolia
 * Source: Voyager API (https://sepolia.api.voyager.online)
 */

import type { Address, Validator } from "@/types";

export const sepoliaValidators = {
  MOONLI_ME: {
    name: "moonli.me",
    stakerAddress:
      "0x003bc84d802c8a57cbe4eb4a6afa9b1255e907cba9377b446d6f4edf069403c5" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/y3v63n/eigenlayer/refs/heads/main/logo_new.png"
    ),
  },
  TEKU: {
    name: "Teku",
    stakerAddress:
      "0x068b5f8e8eb23a42ad290800f229f09b1bcc8d43537dd27a127769ffa13b59f1" as Address,
    logoUrl: new URL(
      "https://www.teku.network/storage/329/9f17e1dd-c4ac-4b58-a46c-8cf36a3a47a4/teku.jpg"
    ),
  },
  ONCHAINAUSTRIA: {
    name: "onchainaustria",
    stakerAddress:
      "0x0771f68ba376b6507a7d21e15d04d48aa6563ea131f89668b92be06707218741" as Address,
    logoUrl: new URL(
      "https://onchainaustria.at/wp-content/uploads/2023/02/OCA_ICON_500x500.png"
    ),
  },
  CROUTONDIGITAL: {
    name: "CroutonDigital",
    stakerAddress:
      "0x05862ff0bf252dcd0a872104ffcf04a33d8ee9a48d4ef2d5c548147046502502" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Crouton-Digital/Eigenlayer/main/logo.png"
    ),
  },
  DSRV: {
    name: "DSRV",
    stakerAddress:
      "0x0789447b5b58aaa87e8ac285288b39bc806aefbc056e49947eb531f7088334ea" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/8349f3ab6852a8419c1987ad9096c605_360_360.jpg"
    ),
  },
  THEBUIDL: {
    name: "TheBuidl",
    stakerAddress:
      "0x05469d2d0be78cb53c0e806b7a68e5f492c221b4faeccebe6532372f2a32d63c" as Address,
    logoUrl: new URL("https://thebuidl.org/logo.svg"),
  },
  KEPLR: {
    name: "Keplr",
    stakerAddress:
      "0x0400dd26dd8802d94d36c780dd67e03d9a6f9922ab25557ca52d36b64484029d" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/daniel-ck89/keplr-starknet-validator-logo/refs/heads/main/keplr.svg"
    ),
  },
  SATOSHI_UNIVERSITY: {
    name: "Satoshi University",
    stakerAddress:
      "0x07366b7faf47122ca71f3cfab7044d67f536f6269666886a5f618dad3de745eb" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1853363775728222208/--09lrAv_400x400.jpg"
    ),
  },
  CUMULO: {
    name: "Cumulo",
    stakerAddress:
      "0x02ed848a45985f6715f5955368597f1bbc7f140b1d16e04d40ca28a921e59657" as Address,
    logoUrl: new URL("https://cumulo.pro/images/logocumulo.jpg"),
  },
  STAKECITO: {
    name: "Stakecito",
    stakerAddress:
      "0x0066e43fdd1aacb56c2376506320946304f506d7ee336732bf4b5e2dee803b65" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/stakecito/resources/8fbc9b192acfde6cd09c23385f18fb27a17675d5/logo_stakecito.jpeg"
    ),
  },
  NETHERMIND: {
    name: "Nethermind",
    stakerAddress:
      "0x05c85dd30df86ed1f2cfe1806417efb2cae421bffdee8110a74a3d3eb95b28d3" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/63bcd69729ab7f3ec1ad210a/663108aa73a8b9bfcd3dc6ae_Nethermind_Icon_Bottom_Banner.svg"
    ),
  },
  STAKETAB: {
    name: "Staketab",
    stakerAddress:
      "0x00499fafce1bea62ba9173b14230b070a38e2c0646af72ce5c8ef89244746611" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Staketab/Eigenlayer-metadata/main/operator/logo.png"
    ),
  },
  STAKINGCABIN: {
    name: "StakingCabin",
    stakerAddress:
      "0x0014daa18b0a151e5a65c5c14b26e3cf7d93c67b574dc71ae0eebe0b0c7eba31" as Address,
    logoUrl: new URL(
      "https://stakingcabin.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo.bafb5657.webp&w=1920&q=75"
    ),
  },
  PROVALIDATOR: {
    name: "Provalidator",
    stakerAddress:
      "0x07b33ad30c05e53eaa4ceb49109a3bb792f92abbf88419eb37e88e8cd8f994e0" as Address,
    logoUrl: new URL(
      "https://media.licdn.com/dms/image/v2/D560BAQHeyCDZipMAPg/company-logo_200_200/company-logo_200_200/0/1687103810506/provalidator_logo?e=2147483647&v=beta&t=IybW6Fa_Cg14WHM5PCkSZ3ap7-14KtWz-FaEqK0jheE"
    ),
  },
  MOONLET: {
    name: "Moonlet",
    stakerAddress:
      "0x021cc70cba5befc5f8089915a3c97c24a7fa9207327c1383e0544c4346ff61fb" as Address,
    logoUrl: new URL("https://images.moonlet.cloud/moonlet.png"),
  },
  VALIDATION_CLOUD: {
    name: "Validation Cloud",
    stakerAddress:
      "0x02be4cad0d88c68bbbcdc38cb3c554f922d39b2193f7eb0ff890f4e47ea2ab91" as Address,
    logoUrl: new URL(
      "https://vc-marketing-website-assets.s3.us-west-2.amazonaws.com/vc-logo.png"
    ),
  },
  KEYSTONE_NODES: {
    name: "Keystone Nodes",
    stakerAddress:
      "0x06f13b9ced21e0fd06c0cc3d14f09550e979696d0f7cc05ff7db12244129e06f" as Address,
    logoUrl: new URL("https://i.ibb.co/MB4KbZ1/keystone-nodes-logo.jpg"),
  },
  CHORUS_ONE: {
    name: "Chorus One",
    stakerAddress:
      "0x07636ead6307de79a40d609ba8e581d65a959f74882e6ed08345653819eb8e05" as Address,
    logoUrl: new URL("https://chorus.one/logo-360x360.jpg"),
  },
} as const satisfies Record<string, Validator>;
