/**
 * Staking validator presets for Starknet mainnet.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: npx tsx scripts/generate-validator-presets.ts --network mainnet
 * Source: Voyager API (https://api.voyager.online)
 */

import type { Address, Validator } from "@/types";

export const mainnetValidators = {
  KARNOT: {
    name: "Karnot",
    stakerAddress:
      "0x072543946080646d1aac08bb4ba6f6531b2b29ce41ebfe72b8a6506500d5220e" as Address,
    logoUrl: new URL(
      "https://framerusercontent.com/images/uGXghZXK5r0SWNIiJdjpAL6kdE.png"
    ),
  },
  READY_PREV_ARGENT: {
    name: "Ready (prev. Argent)",
    stakerAddress:
      "0x00d3b910d8c528bf0216866053c3821ac6c97983dc096bff642e9a3549210ee7" as Address,
    logoUrl: new URL(
      "https://dv3jj1unlp2jl.cloudfront.net/argent-assets/hito-orange-on-white.png"
    ),
  },
  TWINSTAKE: {
    name: "Twinstake",
    stakerAddress:
      "0x01aca15766cb615c3b7ca0fc3680cbde8b21934bb2e7b41594b9d046d7412c00" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/102983825?s=80&v=4"
    ),
  },
  AVNU: {
    name: "AVNU",
    stakerAddress:
      "0x036963c7b56f08105ffdd7f12560924bdc0cb29ce210417ecbc8bf3c7e4b9090" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/128681321?s=200&v=4"
    ),
  },
  BRAAVOS: {
    name: "Braavos",
    stakerAddress:
      "0x04b00f97e2d2168b91fe64ceeace4a41fc274a85bbdd0adc402c3d0cf9f91bbb" as Address,
    logoUrl: new URL("https://assets.braavos.app/images/icons/braavos.svg"),
  },
  ANCHORAGE_DIGITAL: {
    name: "Anchorage Digital",
    stakerAddress:
      "0x071995e702c5c3f27a991c33aa080b278435ce014e422ef1dfe80ff1420e3fc1" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1597615022133354499/jJsLNXTH_400x400.png"
    ),
  },
  BINANCE: {
    name: "Binance",
    stakerAddress:
      "0x0785ba32c2d07462534d523b48f908ff4a6360cb702749e83566239341ed6aae" as Address,
    logoUrl: new URL(
      "https://public.bnbstatic.com/20190405/eb2349c3-b2f8-4a93-a286-8f86a62ea9d8.png"
    ),
  },
  BITWISE_ONCHAIN_SOLUTIONS: {
    name: "Bitwise Onchain Solutions",
    stakerAddress:
      "0x043a242b45c03683e2acc96bb7d207c0cfec6d554b224c76c3b690960b485adb" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/attestantio/eigenlayer-public/refs/heads/main/dark.png"
    ),
  },
  NETHERMIND: {
    name: "Nethermind",
    stakerAddress:
      "0x02952d1e0de1de08fbe6a75d9d0e388e3e89d5d9d42d5f85906ec42ea02e35de" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/63bcd69729ab7f3ec1ad210a/663108aa73a8b9bfcd3dc6ae_Nethermind_Icon_Bottom_Banner.svg"
    ),
  },
  NANSEN: {
    name: "Nansen",
    stakerAddress:
      "0x064204710398bbd2a3af22b9335f4d75234f16e5badb5210b686232f2333d9f1" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/60118ca18674407b85935203/64f8addec0663119ef4499dd_Logo_nansen.svg"
    ),
  },
  PRAGMA: {
    name: "Pragma",
    stakerAddress:
      "0x077d4b4e7ae321aabd0a5a7322108635fcbd0cd746f9ae217b8ea00363494b65" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1759587821097005056/kG97ii_u_400x400.png"
    ),
  },
  CARBONABLE: {
    name: "Carbonable",
    stakerAddress:
      "0x015cc95c70120ec985bdd6115232dd5f875bd58820aa4c62b6565d0fe33c3ac4" as Address,
    logoUrl: new URL(
      "https://github.com/Carbonable/carbonable.github.io/blob/main/assets/logo/logo_dark.png?raw=true"
    ),
  },
  KEPLR: {
    name: "Keplr",
    stakerAddress:
      "0x070ff78577847c55027d6defb5f7613714e052e47235fe8e7bac7c0915a8e08f" as Address,
    logoUrl: new URL(
      "https://keplrinfralogo.s3.us-west-2.amazonaws.com/KI.png"
    ),
  },
  CARTRIDGE: {
    name: "Cartridge",
    stakerAddress:
      "0x03f7f4e5a23a712787f0c100f02934c4a88606b7f0c880c2fd43e817e6275d83" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1845153042762436629/LZs7_I2b_400x400.jpg"
    ),
  },
  ZELLIC: {
    name: "Zellic",
    stakerAddress:
      "0x04092a9c00457c6596009ca3feca4c028ad95e431d8683b5b1fdd591ede140fc" as Address,
    logoUrl: new URL("https://assets.zellic.io/pfp.jpg"),
  },
  FIGMENT: {
    name: "Figment",
    stakerAddress:
      "0x043b0063dc54167904d67344fff77e0a628182008f85dd0d650e4f84f7f70066" as Address,
    logoUrl: new URL(
      "https://figment-logo.s3.ca-central-1.amazonaws.com/Figment-logo.png"
    ),
  },
  HERODOTUS: {
    name: "Herodotus",
    stakerAddress:
      "0x034cadb95a1e54a258d5a711a7be052ca5a8582cadebf7dfc50d11db8d6b19b5" as Address,
    logoUrl: new URL("https://i.ibb.co/DHz6dnrL/Herodotus-Profile.png"),
  },
  FIBROUS: {
    name: "Fibrous",
    stakerAddress:
      "0x032329f284ebe262e368afba0049ba025ed5999fe1d8da1aa710c9ad5f8c53aa" as Address,
    logoUrl: new URL("https://app.fibrous.finance/icon.png"),
  },
  P2P_ORG: {
    name: "P2P.org",
    stakerAddress:
      "0x071768d9d5468cac52c7f4b0f1265fecd7cb1a9733dfa453a27aaf900a6946a8" as Address,
    logoUrl: new URL("https://i.postimg.cc/hPJS6ygY/temp-Image-RKea-K4.avif"),
  },
  STAKEFISH: {
    name: "stakefish",
    stakerAddress:
      "0x02db5d9947e213aa9c309f656b8b80592c891d02635c41289748dc0805289753" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/stakefish/stakefish-metadata/main/stakefish-logo.png"
    ),
  },
  ONCHAINAUSTRIA: {
    name: "onchainaustria",
    stakerAddress:
      "0x072c6aa4f9f84fad52de9e70b1fc97347e20716935801c4df0cce5b171718e4e" as Address,
    logoUrl: new URL(
      "https://onchainaustria.at/wp-content/uploads/2023/02/OCA_ICON_500x500.png"
    ),
  },
  TEKU: {
    name: "Teku",
    stakerAddress:
      "0x068b5f8e8eb23a42ad290800f229f09b1bcc8d43537dd27a127769ffa13b59f1" as Address,
    logoUrl: new URL(
      "https://www.teku.network/storage/329/9f17e1dd-c4ac-4b58-a46c-8cf36a3a47a4/teku.jpg"
    ),
  },
  ARGUS: {
    name: "Argus",
    stakerAddress:
      "0x015b2439195e5c2965d9ccdfabe51f3adaa8c2f92d449d4112deb7a1c07be6e9" as Address,
    logoUrl: new URL(
      "https://i.imgur.com/oKMSRXx_d.webp?maxwidth=760&fidelity=grand"
    ),
  },
  CHAINBASE_STAKING: {
    name: "Chainbase Staking",
    stakerAddress:
      "0x074f53494d13a3789e693e6cfca510d80fcc8eff6c09e6e1f406492595b518bc" as Address,
    logoUrl: new URL("https://static.chainbase.online/chainbase_staking.svg"),
  },
  POSTHUMAN_STAKEDROP: {
    name: "POSTHUMAN 🧬 StakeDrop",
    stakerAddress:
      "0x0327478b645a0c6889e995fe22b1298fae420dba24cc42422f0c066763d08dc9" as Address,
    logoUrl: new URL(
      "https://github.com/Validator-POSTHUMAN/brand-book/blob/main/POSTHUMAN%20LOGO%20Vector%20512.png?raw=true"
    ),
  },
  VENTORY: {
    name: "Ventory",
    stakerAddress:
      "0x00edd59ca1932462718c81ef4d7f463fed50e29f8a11b24d7cb5d8373923b786" as Address,
    logoUrl: new URL("https://ipfs.ventory.gg/ventory/media/fun.png"),
  },
  NEOZARU: {
    name: "neozaru",
    stakerAddress:
      "0x034e5b8fd71033cac6bf40478736ddac340097ab1f3002a61505fdabe342ac0f" as Address,
    logoUrl: new URL("https://neozaru.ovh/neozaru-logo.webp"),
  },
  SANIKSIN: {
    name: "Saniksin",
    stakerAddress:
      "0x0475a1ba31db59f0eda3b3b260ad3abb30a2a67983cd51d753fdb4adad92a524" as Address,
    logoUrl: new URL("https://i.ibb.co/XpP3jtm/YIE4m-Fj-Imgur.png"),
  },
  STAKECITO: {
    name: "Stakecito",
    stakerAddress:
      "0x0655ab8f44bdaeab14c4826383a65af75c21cef9b0cabb018519eed7120c93e3" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/stakecito/resources/8fbc9b192acfde6cd09c23385f18fb27a17675d5/logo_stakecito.jpeg"
    ),
  },
  SLUH_AI: {
    name: "sluh.ai",
    stakerAddress:
      "0x02d86897daadee2dffdb5c5b734ab568fe849808105977e0384f8e5d1a0d33d7" as Address,
    logoUrl: new URL(
      "https://sluh.ai/ncsitebuilder/gallery/favicons/favicon.png"
    ),
  },
  ALLNODES: {
    name: "Allnodes",
    stakerAddress:
      "0x002843700bd4bc546d05baa55d055572bf2beea8ebefbdb9be763f83638fc294" as Address,
    logoUrl: new URL("https://www.allnodes.com/img/allnodes_circle_symbol.svg"),
  },
  _0XRASPNODE: {
    name: "0xRaspnode",
    stakerAddress:
      "0x05ff6a0b57ad4a65981ea21e064d0308e8e01d5d23f293a688062d2aa31f940e" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1932474474038767616/3T-wDAkj_400x400.jpg"
    ),
  },
  STEAK_LI: {
    name: "steak.li",
    stakerAddress:
      "0x05d0eb74795283001ae399656e00a194e6e83479ae7a537f4986ad5bc39f22bc" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1863682364989210624/tF_xEhP9_400x400.jpg"
    ),
  },
  BYANASTASIIA: {
    name: "ByAnastasiia",
    stakerAddress:
      "0x0018b139707cf26a62b7b38b5bd7859dab1b4965f29db4d330534ff38a10a22d" as Address,
    logoUrl: new URL("https://i.ibb.co/VYFy1KM7/ava-80x80.png"),
  },
  NORVOS: {
    name: "Norvos",
    stakerAddress:
      "0x05c755ba1828c70314349ec4c4ddaf310e648d5773f9bb6c4eb6ce2369288569" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/184258039?s=200&v=4"
    ),
  },
  NODESTAKE: {
    name: "NodeStake",
    stakerAddress:
      "0x04ee3fab423424352d4fc7dd1a3bb6d26a34c26f0793e94f89d02a210d961448" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/nodestake/brand-kit/refs/heads/main/logo.png"
    ),
  },
  EUROPA_VALIDATOR: {
    name: "Europa Validator",
    stakerAddress:
      "0x054fe9375a6b69d5126f54fc447a99ad55bc24b4282f6d9ade977817d780f8dc" as Address,
    logoUrl: new URL(
      "https://europa-cro-node.xyz/assets/images/europa_node_validator_logo_460px.png"
    ),
  },
  BITSZN: {
    name: "bitszn",
    stakerAddress:
      "0x05b625f0a99bbdb24fbe88cf481e8559e26c0d1d2ac6d957fb77f556857c7543" as Address,
    logoUrl: new URL("https://bitszn.com/bitszn.svg"),
  },
  WEB34EVER: {
    name: "web34ever",
    stakerAddress:
      "0x067f8dc84b5b2213c4ec5a4df990f7324bf025bb819ec2e9b7592e5c82fa4bab" as Address,
    logoUrl: new URL("https://avatars.githubusercontent.com/u/59205554"),
  },
  FRUTERO_CLUB: {
    name: "Frutero Club",
    stakerAddress:
      "0x043f05485eafa41da1cd8442069a72a6264dfced0ad1af298fd235d6df91f735" as Address,
    logoUrl: new URL("https://criptochingaderas.com/frutero/logo.png"),
  },
  SENSEINODE: {
    name: "SenseiNode",
    stakerAddress:
      "0x01d83071fef0e55608b3971c80a894285cce7ae11f59d0cc2beb83c68214bb0a" as Address,
    logoUrl: new URL("https://i.postimg.cc/pV9rMFFd/Logo-solo.png"),
  },
  BLOCKPRO: {
    name: "BlockPro",
    stakerAddress:
      "0x03baeda4f84b8a7ff49b534e51cef2d033c19baf9aac552033f25de5f74d216a" as Address,
    logoUrl: new URL("https://i.postimg.cc/k5QQYwGF/logo.png"),
  },
  GOLDINTERNATION: {
    name: "GoldInternation",
    stakerAddress:
      "0x03936bf43887657f80eda16c564a14f66fb5e99bc18f2b5b8a93a6cbd1a6658e" as Address,
    logoUrl: null,
  },
  OLDIRTYBENJI: {
    name: "OlDirtyBenji",
    stakerAddress:
      "0x03c192719026b8f2208e1b8891a9db5cde8b90229a33c02f69f3c0eb07771170" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/4759807?s=400&u=1367e8e3307b02aef996d930feafa29937ccb5b9&v=4"
    ),
  },
  STAKELY: {
    name: "Stakely",
    stakerAddress:
      "0x03fd204025bf226e71a45f94564c1199b95b80a05c45db3d827e4004c6b30ece" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/89227807?s=96&v=4"
    ),
  },
  SETHEE_IT_LTD: {
    name: "Sethee IT LTD.",
    stakerAddress:
      "0x07037044bca2a03ac5f317c8193f71dc49fe0aafa9acbcbb8c994d49f18e7cb3" as Address,
    logoUrl: new URL("https://i.imgur.com/heKv4QA.png"),
  },
  FLOY: {
    name: "Floy",
    stakerAddress:
      "0x02958759e22b48cfc703480c74ba9197df26190c78b83e99f25e96148b932160" as Address,
    logoUrl: new URL("https://i.imgur.com/XXXT9Xb.jpeg"),
  },
  ARCHETYPAL_TECH: {
    name: "Archetypal Tech",
    stakerAddress:
      "0x0234cbb9f4f867f5e6b71f70d20695a9a18ad34d203d87235a6305843f8b8788" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/ArchetypalTech/press--oruggintrail/refs/heads/main/src/routes/images/ArchetypalLogo-2024-WhiteWiBG.png"
    ),
  },
  NODE101: {
    name: "node101",
    stakerAddress:
      "0x0329de61cdda3e8ff4e69b57cb21bded4ba026fc13f007344053e59737597bb0" as Address,
    logoUrl: new URL("https://node101.io/img/logo.svg"),
  },
  BUBBLE_STUDIO: {
    name: "Bubble Studio",
    stakerAddress:
      "0x07cd517c4373c8f6e879b24cefae63cedb3ef7e06f5fef033cde6ab734da441e" as Address,
    logoUrl: new URL(
      "https://cdn.jsdelivr.net/gh/cauu/bubble-studio-assets@main/images/logos/bubble-logo.png"
    ),
  },
  BONOUT: {
    name: "Bonout",
    stakerAddress:
      "0x03912bf7ee089d66bf3d1e25af6b7458bdb4e4a17dbad357cbcfd544830f79ea" as Address,
    logoUrl: new URL("https://bonout.com/plain-icon.png"),
  },
  ITROCKET: {
    name: "ITRocket",
    stakerAddress:
      "0x03e578ec6757bd366a43c8157dab6fbf6491639173c42ae85f383a479fc90102" as Address,
    logoUrl: new URL(
      "https://server-3.itrocket.net/brand_kit/ITRocket_brand_kit/full/png/icon_black_bg+centre.png"
    ),
  },
  THEBUIDL: {
    name: "Thebuidl",
    stakerAddress:
      "0x01013a4c93848da7e4c3b6c8768daedc1b1ca8478df5fa3e5198d037e833acca" as Address,
    logoUrl: null,
  },
  J_NODE: {
    name: "J•Node",
    stakerAddress:
      "0x00ac906005b8ec20c51b3d0a9f971a589bfbe6226205f61561091c900522d773" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Josephtran102/explorer-validator-profiles/refs/heads/main/images/891BC6B7C0D28458.png"
    ),
  },
  ENCAPSULATE: {
    name: "Encapsulate",
    stakerAddress:
      "0x0359e252e663765989b04c266a4daec77662b506ce5f026994cb8ad53628df2a" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/encapsulate-xyz/assets/refs/heads/main/encapsulate.png"
    ),
  },
  STAKEUP: {
    name: "StakeUp",
    stakerAddress:
      "0x07d915cdeae00b4460979985a18bcc71597153aaa4d02ca293bfd943c1286316" as Address,
    logoUrl: new URL("https://stakeup.tech/assets/images/logo.png"),
  },
  DTEAM: {
    name: "DTEAM",
    stakerAddress:
      "0x001dbd42a6e91ceca28d1364acc31f9e73c1419b2624ce30874ade81e8324e04" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/DTEAMTECH/identity/refs/heads/main/logo.png"
    ),
  },
  STINGRAY: {
    name: "StingRay",
    stakerAddress:
      "0x07a97a7662e7f634c8f1d136cbd1f4d46b4c9551ba5f7df0c32b3d6a07f0f1cd" as Address,
    logoUrl: new URL(
      "https://github.com/MikhailRadusha/MikhailRadusha/blob/76dd5cec1c1237980cccb300d8369e84422406b8/logo/logo.png?raw=true"
    ),
  },
  PERFECT_NODES: {
    name: "Perfect-nodes",
    stakerAddress:
      "0x041633461e3a1136edc1c31b3c26db2c07e0c179b0036255994bdb01e714d3d4" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/99a37637a07799aa133e458be51b0205_360_360.jpg"
    ),
  },
  GAME_MACHINE_LABS: {
    name: "Game Machine Labs",
    stakerAddress:
      "0x055c697c985f745587991a3f16f068a59f0241bd66e05564ce5a7a9cc1e43664" as Address,
    logoUrl: new URL("https://www.gamemachinelabs.xyz/logo/gm-logo-small.png"),
  },
  VAUBAN: {
    name: "Vauban",
    stakerAddress:
      "0x07e7e6103fa8d6365860ec14d3f14ec9cd9b55b79e5c7bf8dc13a95bf83acaa2" as Address,
    logoUrl: null,
  },
  CRYPTONATIVE_SYSTEMS: {
    name: "cryptonative.systems",
    stakerAddress:
      "0x04c2b0e230aef0c703594d899c142d6aa6e1c9d43bf7032eec4d1bdb3c944aa4" as Address,
    logoUrl: new URL(
      "https://cryptonative.systems/wp-content/uploads/2023/12/cropped-Cryptonative.png"
    ),
  },
  MOONLI_ME: {
    name: "moonli.me",
    stakerAddress:
      "0x035f074ab2ce04af70c1d1cce3658d5b264cb3fde49f1c1809695929b021d1d5" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/y3v63n/eigenlayer/refs/heads/main/logo_new.png"
    ),
  },
  M_E_D_I_U_M_R_A_R_E: {
    name: "M E D I U M ⬩ R A R E",
    stakerAddress:
      "0x021a5797cd9e8f74117bfa2771fb7fe0d3eff6bee06de4b52657fcd97234dad2" as Address,
    logoUrl: new URL(
      "https://i.postimg.cc/05tjhCSq/medium-rare-node-700x700.png"
    ),
  },
  BAREMETAL_LIVE: {
    name: "BareMetal.live",
    stakerAddress:
      "0x076ffc55e02865335b712858e26eb08557528c72c02a623c03b27f7a6a06d9fd" as Address,
    logoUrl: new URL("https://baremetal.live/BareMetal-logo-sm.png"),
  },
  NODZ: {
    name: "Nodz",
    stakerAddress:
      "0x003858ccd8211c5ddb97af0ccd5cf8f00f2093d0d10d712f048d4bf8e3eee1f5" as Address,
    logoUrl: new URL("https://nodz.io/images/icon/nodz-400x400.png"),
  },
  STAKELAB_ZONE: {
    name: "StakeLab.zone",
    stakerAddress:
      "0x026117b3c5a137220ba581b95bb0bd72fcd43ca789ba23ffcd13978fd0b8cf32" as Address,
    logoUrl: new URL(
      "https://github.com/zdeadex/chainlist/blob/main/chain/akash/moniker/akashvaloper1dgxdep80th2qm8xxk8h3j3g93npsd3a8jg60gz.png?raw=true"
    ),
  },
  STAKETAB: {
    name: "Staketab",
    stakerAddress:
      "0x0744c4e52110f5c463d1997a5989a73ce97087628182a126ccaaabc65e526249" as Address,
    logoUrl: new URL(
      "https://brand-staketab.s3.eu-north-1.amazonaws.com/staketab/twitter.png"
    ),
  },
  UNDERWARE: {
    name: "Underware",
    stakerAddress:
      "0x04c9bd490305796b88852d6f57862f9eda26c8af30c240cc68e9cfb785e79525" as Address,
    logoUrl: new URL("https://assets.underware.gg/underware-blackBG.png"),
  },
  ATTENDANTES: {
    name: "Attendantes",
    stakerAddress:
      "0x012ae285a6692f2ac00811aa75e8a3c8d94367cba22e22e581e2b51e3bde5103" as Address,
    logoUrl: null,
  },
  HIGHTOWER: {
    name: "HighTower",
    stakerAddress:
      "0x01a533ba647460b2a292c85a58e4011459cc29b50e37663d05f5f8f4fa9d6f6b" as Address,
    logoUrl: new URL("https://brand-kit.htw.tech/logo/logo_green_80x80.png"),
  },
  STAKING4ALL: {
    name: "Staking4All",
    stakerAddress:
      "0x0586a61016dfb1967e3eb227b048a1331e640851a9998b251d2da2385fbb066e" as Address,
    logoUrl: new URL("https://x.com/staking4all/photo"),
  },
  RUNELABS: {
    name: "Runelabs",
    stakerAddress:
      "0x0551a33db7f01ab71d8b272a33260629893b7e3d602267cd0a06b91017a1079a" as Address,
    logoUrl: new URL(
      "https://runelabs-assets.s3.fr-par.scw.cloud/validator/RuneLabValidatorLogo.svg"
    ),
  },
  SIMPLY_STAKING: {
    name: "Simply Staking",
    stakerAddress:
      "0x066c107682457a2cecb99f803f312bf98e92a3692f18c8ae4cee5c9f056ae0a5" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/27d4669503119b84bbc4bd4ae7f0bf05_360_360.jpg"
    ),
  },
  R1M: {
    name: "R1M",
    stakerAddress:
      "0x0025ba2f802c73e24ae23ed4f43f6b7e9d38b14f8fea947c322d80c809571c54" as Address,
    logoUrl: new URL("https://labs.r1m.team/images/logo.png"),
  },
  NONNYJOE: {
    name: "Nonnyjoe",
    stakerAddress:
      "0x07bcc23ef59476c2dc09218afae71405e295ed58442ece796ce22a0b04adb571" as Address,
    logoUrl: null,
  },
  DAS_RHEINGOLD: {
    name: "Das.Rheingold",
    stakerAddress:
      "0x04c2e99661a85fec90cc66fec5b1eb911a0633888f468f3eac6b9654191f7102" as Address,
    logoUrl: null,
  },
  CUMULO: {
    name: "Cumulo",
    stakerAddress:
      "0x0327a835fda4673a83f63d90bc3a16dd5b1645972acd539b3fc2446e73b11170" as Address,
    logoUrl: new URL("https://cumulo.pro/images/logocumulo.jpg"),
  },
  MERIA: {
    name: "Meria",
    stakerAddress:
      "0x03b85f34efde020c700065306d1a9c81f98d242bd88c2721a7e82d2759ffd799" as Address,
    logoUrl: new URL(
      "https://www.meria.com/images/branding/logo-line-color.svg"
    ),
  },
  DAPRIDDLE: {
    name: "dapriddle",
    stakerAddress:
      "0x016cacb599999b339988695c2721c65186ccc41529fb12a7b7a9251c163dc590" as Address,
    logoUrl: new URL("https://euc.li/dapriddle.eth"),
  },
  OLEHZUSKO: {
    name: "OlehZusko",
    stakerAddress:
      "0x013d212e2d1bcf50cc5af3c01b3b27f4a7484e3df8dd926b0d83fb7f6c6b5fc7" as Address,
    logoUrl: new URL("https://i.ibb.co/hRsRjs7P/oleh-80x80.png"),
  },
  IANAZ: {
    name: "ianaz",
    stakerAddress:
      "0x004272a304e8e9eee7b77ce26df3450af12c9eb6bb608c3ccb7323fd3b7f4089" as Address,
    logoUrl: new URL("https://dummyimage.com/80/80/fff.png&text=ianaz"),
  },
  CROUTONDIGITAL: {
    name: "CroutonDigital",
    stakerAddress:
      "0x05aac4ebc80e3ac465be66ee959523c2f904adfc817d9e4d80d7cfc327a2def7" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Crouton-Digital/Eigenlayer/main/logo.png"
    ),
  },
  CRYPTO_ROOM: {
    name: "Crypto_room",
    stakerAddress:
      "0x0131383f4ad42c6ca411003c7f4113f61eba7b5848c6a1f5a7866661ed8d59c6" as Address,
    logoUrl: new URL(
      "https://investfuture.ru/files/useful_articles/1685438916.png"
    ),
  },
  WOLFEDGE_LABS: {
    name: "WolfEdge Labs",
    stakerAddress:
      "0x0749c29eddd24613c320b57cf9299a2694934e5e3fabce987df1784231edba71" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1626528229095014400/14ABq3ll_400x400.jpg"
    ),
  },
  CHAINLABO: {
    name: "ChainLabo",
    stakerAddress:
      "0x023a5db82cc948dfc52fe43e3567df672611e530432034e6b947e28e8e069661" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/67ece4798f1f4c385f56be43/680a1e40890f8dfe8dcef159_cl_logomark_color_256.jpeg"
    ),
  },
  TRUST_YOUR_TECHNOLUST: {
    name: "Trust Your Technolust",
    stakerAddress:
      "0x01012c7ce5ed1a11964e5609d58a4db9154f373f41adee673416b1e07fcf6d90" as Address,
    logoUrl: new URL("https://trustyourtechnolust.xyz/icon.svg"),
  },
  ALPHATEAM: {
    name: "alphateam",
    stakerAddress:
      "0x0786e60c09a183406dce74b279a3010ad2e20fb3d3b831ecd5a2d94a0f7abd0d" as Address,
    logoUrl: null,
  },
  ASGARD: {
    name: "Asgard",
    stakerAddress:
      "0x052e77b9ad9e736efa1e7444227b9a06ea0aae7fb0de5e85c63145dc3b86e081" as Address,
    logoUrl: new URL(
      "https://static.tildacdn.info/tild3265-3331-4439-a662-623732623335/asgard-logo.png"
    ),
  },
  INFRASINGULARITY: {
    name: "InfraSingularity",
    stakerAddress:
      "0x0043b2d0a0c549298567fa7b4b992f4fddf9e38f9819b7749cdf885e2b0023dd" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/varunsh-is/is-logo/refs/heads/main/IS-logo-square-short.png"
    ),
  },
  CYPHER_NETWORKS: {
    name: "Cypher Networks",
    stakerAddress:
      "0x00bb6c4af7ea20ce5f02cb706c7cdc897ee6a5c44c4dceb9fb87e58f0c8102cf" as Address,
    logoUrl: new URL("https://cyphernetworks.xyz/assets/logo.png"),
  },
  CURIOSITY: {
    name: "Curiosity",
    stakerAddress:
      "0x060b86bbcc85ea9ef0f6bb4bd7eaaf3bd4c917ee304d28470b94c8aa4d0910b1" as Address,
    logoUrl: new URL(
      "https://drive.google.com/file/d/1fz04x3-62edZhx0SajVR0LYQ9Tnmttqe/view?usp=sharing"
    ),
  },
  DENODES: {
    name: "deNodes",
    stakerAddress:
      "0x008dc7841f346706b718efc94062796ca6cba553728056b1ad8f99926f16f483" as Address,
    logoUrl: new URL(
      "https://avatars.githubusercontent.com/u/139079136?s=400&u=4ff64afa0f64e7420c5c12e9a1d41daf23de865c"
    ),
  },
  COINHUNTERS: {
    name: "CoinHunters",
    stakerAddress:
      "0x032daa3370a015a0737bc4e358bc1a2f6e999a5781b21057e9b43a0dc8334f92" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1603069058601172994/ASviUmE3_400x400.jpg"
    ),
  },
  MOST_YIELD: {
    name: "Most Yield",
    stakerAddress:
      "0x063b0a2075e06b72891ba62108aff51d302e3cadd867a06fcd776e452c895da1" as Address,
    logoUrl: new URL("https://i.ibb.co/0jXSd3Jx/Most-on-white-back.png"),
  },
  AURI_0X: {
    name: "Auri_0x",
    stakerAddress:
      "0x011984bfc315a132677992d8a3da8487bf3ad39842cbc4c3cdfde56d67525fab" as Address,
    logoUrl: new URL("https://i.imgur.com/qzX7Dab.jpeg"),
  },
  HOODRUN: {
    name: "HoodRun",
    stakerAddress:
      "0x018231b7efb19f71c0a938ed876ed98afb864f716d52f2b9ee43719a953d3453" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/a1600c5650b26f850982dac401912305_360_360.jpg"
    ),
  },
  NODERS_TEAM: {
    name: "NODERS TEAM",
    stakerAddress:
      "0x00e154198809f2ae5e5425888719c74abc3ff133583c7746c64d437c0320b0da" as Address,
    logoUrl: new URL("https://noders.services/img/logo.svg"),
  },
  STAKEANGLE: {
    name: "StakeAngle",
    stakerAddress:
      "0x03127b2a195d8dfa8a78d22c6883d97ae4fa3219f9e6463d7bb821dbfd0d3cce" as Address,
    logoUrl: new URL("http://stakeangle.com/StakeAngle_logo.png"),
  },
  ANYVALID: {
    name: "AnyValid",
    stakerAddress:
      "0x07a2d301fd29171ab96d9f1b24d1db5d2649e6ea97630de620cbcae54c680f55" as Address,
    logoUrl: new URL("https://anyvalid.com/images/AnyValid.png"),
  },
  MEDIUM: {
    name: "medium",
    stakerAddress:
      "0x0610e4e6326a757317a09c451fd242e7c6c4118372dec8660be3bf2e99261268" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/mediumwe11/medium-logo/main/medium%20logo.png"
    ),
  },
  WOMBAT: {
    name: "wombat",
    stakerAddress:
      "0x04e5a86ed9e29127e0157a6c26a82cda109febde872d30b7a27549082951057d" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/wombatqq/wombatqq_logo/main/wombat%20logo.png"
    ),
  },
  NODIUMS: {
    name: "Nodiums",
    stakerAddress:
      "0x0443b3a19a8ef82abab80b1741bef9a99cc533a4e822a4e139fa96017b2007b5" as Address,
    logoUrl: new URL(
      "https://nodiums.com/wp-content/uploads/2024/01/logo-20.png"
    ),
  },
  OWLSTAKE: {
    name: "OwlStake",
    stakerAddress:
      "0x00af5b577ec756cef1c21dc3e7bd13e02b2f3677926b8d6ee2ff2a4256b7f1ca" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/owlstake/owlstake/refs/heads/main/owlstake-logo.png"
    ),
  },
  ONNODE: {
    name: "OnNode",
    stakerAddress:
      "0x04a044a2641974655f8429a04f3e7300e888f93bf7e13d95438ba47d1830a402" as Address,
    logoUrl: new URL("https://onnode.org/img/logo.png"),
  },
  MOONLET: {
    name: "Moonlet",
    stakerAddress:
      "0x05012a0911c6557f3f9f250b7b477681b79eb1e8af78cd02ed6d6092bb92f505" as Address,
    logoUrl: new URL("https://images.moonlet.cloud/moonlet.png"),
  },
  VALIDEXIS: {
    name: "VALIDEXIS",
    stakerAddress:
      "0x02f78b1aa5ea0ff516f0f2aeee20cc980002b7d973899bb6ae5e8d005959cbaf" as Address,
    logoUrl: new URL("https://i.imgur.com/WNbyxJM.png"),
  },
  PICONBELLO: {
    name: "Piconbello",
    stakerAddress:
      "0x0156cf8352b3c55b8a00bc1cb7fa8d157fd6a454a078874abe7e35c0d8f77e69" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/piconbello/Eigenlayer-Goerli/main/Logo.png"
    ),
  },
  ASTROSYNX: {
    name: "Astrosynx",
    stakerAddress:
      "0x02345dfe6a1cac32e9e5c48c47e104281bc766ecdee47cdeeab6028ade7fc003" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/astrosynx/Logo/main/Astrosynx_logo.jpg"
    ),
  },
  CHAIN_DIGITAL: {
    name: "CHAIN DIGITAL",
    stakerAddress:
      "0x023d2174be7e064dc31f3f358c850fc1ab3e05ad5b61ea7479e23843250845d0" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/chaindigital/logo/main/CD.png"
    ),
  },
  HUGINN: {
    name: "Huginn",
    stakerAddress:
      "0x03c3085de545ff2ffc2f267b7dfb87e2977938fd9cdd4c1de4982313ac34f872" as Address,
    logoUrl: new URL("https://i.imgur.com/Da4YW1S.png"),
  },
  SKYNETICLABS: {
    name: "Skyneticlabs",
    stakerAddress:
      "0x0557b00b15bcad5ee10b708b41bd4291f319d4e4bf1fd43bfd88a5391f24318d" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Skyneticlabs/Logo/main/Skyneticlabs.jpg"
    ),
  },
  VALIDATION_CLOUD: {
    name: "Validation Cloud",
    stakerAddress:
      "0x069b9d9fc5064a3c9025ff44c58f0088467a730fddc1e26652afeae003e1ec25" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/653acce1d72443c35298481d/653bbcd87fc49bd75a9b6a3e_Webclip.png"
    ),
  },
  NODE3TECH: {
    name: "Node3Tech",
    stakerAddress:
      "0x06a1b1ebb671b5e257ec3b039ed72f37578dd63cb9cb06f779f2eb7e1b4ddc21" as Address,
    logoUrl: new URL(
      "https://node3tech.io/wp-content/uploads/2025/06/logo2-2048x2048.png"
    ),
  },
  BITBOARD: {
    name: "BitBoard",
    stakerAddress:
      "0x06cd7eb999b4236b94feaf233ed08330e2f1963d26dd6464b002b4b2d17fd517" as Address,
    logoUrl: new URL("https://i.ibb.co/prsNxCct/Board.jpg"),
  },
  SATOSHI_UNIVERSITY: {
    name: "Satoshi University",
    stakerAddress:
      "0x07366b7faf47122ca71f3cfab7044d67f536f6269666886a5f618dad3de745eb" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1853363775728222208/--09lrAv_400x400.jpg"
    ),
  },
  SUBUTAI_OPERATIONAL_HASH_UNIT: {
    name: "Subutai Operational Hash Unit",
    stakerAddress:
      "0x05fc466c785607651c81c416a55ff8ac196fa2673b673770134eb424e1141c7e" as Address,
    logoUrl: new URL("https://sohucorp.com/favicon.png"),
  },
  JONATHAN_LEI: {
    name: "Jonathan LEI",
    stakerAddress:
      "0x0134c52e3cdc4e581b14e79c3ef93becf778fa400309613a85e8d4c64c0265af" as Address,
    logoUrl: new URL("https://avatars.githubusercontent.com/u/19556359"),
  },
  ZKLEND: {
    name: "zkLend",
    stakerAddress:
      "0x033d152598873a307b9abdd7bd5d479cadf1814db4bf87e0f0d61a8f84d0bf63" as Address,
    logoUrl: new URL(
      "https://cdn-images-1.medium.com/fit/c/72/72/1*4k-fGYduKejpOjgExSKFHw.png"
    ),
  },
  WDMASTER: {
    name: "WDMASTER",
    stakerAddress:
      "0x02d3231a0661e52f4326e1a5d40dd6e05396bf994535662fb1e1cf746c14d082" as Address,
    logoUrl: new URL("https://wdmaster.top/logo2.png"),
  },
  KADIUM: {
    name: "Kadium",
    stakerAddress:
      "0x02dc196d0eb72a3ae0cc2298a08e00f6e6a602ef4252a05bd1698cd3b4c06f5c" as Address,
    logoUrl: new URL(
      "https://static.wixstatic.com/media/323c92_c1aed63b54a54480aed327b03d416ad4~mv2.jpg"
    ),
  },
  STARKNET_ASTRO: {
    name: "Starknet Astro",
    stakerAddress:
      "0x0522d45e8d7a57c5d7d68fbc6fab0ad86b60102041f222cefb2a7140d47e4a28" as Address,
    logoUrl: new URL("https://x.com/StarkNetAstroCN/photo"),
  },
  LAVENDER_FIVE_NODES: {
    name: "Lavender.Five Nodes",
    stakerAddress:
      "0x0684f94890702f08d6765836273bf36c2a0cb0aeb949f146803b7e42060f2192" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/c5f0e5c3c88a6194da5277d3eb297805_360_360.jpg"
    ),
  },
  PULSAR_MONEY_BY_ASTRARIZON: {
    name: "Pulsar Money by Astrarizon",
    stakerAddress:
      "0x000c7181c833be28c212d70e858037efde144235931877f5758d306f01d5edd7" as Address,
    logoUrl: new URL("https://pulsar.money/images/logos/logo-black.svg"),
  },
  ATLAS_STAKING: {
    name: "Atlas Staking",
    stakerAddress:
      "0x01eb3ea6a3c0ad3c2503a349cd8acca19ed34fb006045a1518eca93910bea5c2" as Address,
    logoUrl: new URL("https://i.imgur.com/rlNgkp3.png"),
  },
  NFD: {
    name: "NFD",
    stakerAddress:
      "0x00cc9982f738812df69539bb46ff33de66efda1d58c9780528e2bb285dfc299c" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1639189263244771328/eOtERi6W_400x400.jpg"
    ),
  },
  XVERSE: {
    name: "Xverse",
    stakerAddress:
      "0x06fa26c205d3dc788586652435cae77ce42e44fa01c97e24eee7617217322d25" as Address,
    logoUrl: new URL("https://portfolio.xverse.app/portfolio/xverse-logo.svg"),
  },
  ENIGMA: {
    name: "Enigma",
    stakerAddress:
      "0x0224874adf1da0a04bda379862a6187e102ba4152a489199cbf6ab0a7f8259a4" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/Enigma-Validator/enigma-assets/refs/heads/main/enigma-logo.png"
    ),
  },
  IMPERATOR_CO: {
    name: "Imperator.co",
    stakerAddress:
      "0x0161dbe310290d6f1bad9096b02b2eaea765b420ae9a310728837c14bcc48597" as Address,
    logoUrl: new URL(
      "https://framerusercontent.com/assets/3g7RUr5KjBBsz7oPVYjCsqbASnM.svg"
    ),
  },
  PIXELCARTEL: {
    name: "PiXELCARTEL",
    stakerAddress:
      "0x011afa6f1d98aa7235cca417a409d075468c87971fe97b62a7704a4902982159" as Address,
    logoUrl: new URL("https://pixelcartel.xyz/img/logo_pixelcartel_80x80.png"),
  },
  ZKDX: {
    name: "zkDX",
    stakerAddress:
      "0x050f0861c68997f4369db1c3b51cfe8db537fd9ad5fcbb571939a0914acda865" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1648237430544420864/yf2HiM4c_400x400.png"
    ),
  },
  CHAINUP_CLOUD: {
    name: "ChainUp Cloud",
    stakerAddress:
      "0x02de02b88a30d04ac6a49f24cd6d021f8a1e39d8afabcba348795ab29e3d0d31" as Address,
    logoUrl: new URL("http://cloud.chainup.com/logo_80_80.png"),
  },
  DSRV: {
    name: "DSRV",
    stakerAddress:
      "0x03ba5c922cc9bbde55a41d51c2eba6027c653da318f1956c2405d42451d8e3a8" as Address,
    logoUrl: new URL(
      "https://s3.amazonaws.com/keybase_processed_uploads/8349f3ab6852a8419c1987ad9096c605_360_360.jpg"
    ),
  },
  COMPASS: {
    name: "Compass",
    stakerAddress:
      "0x06711b0f4b310b41585dd80422588f8582db9307685a83eefbc9d4e9b00e6516" as Address,
    logoUrl: new URL(
      "https://raw.githubusercontent.com/cosmostation/chainlist/master/chain/cosmos/moniker/cosmosvaloper1ff0dw8kawsnxkrgj7p65kvw7jxxakyf8n583gx.png"
    ),
  },
  KEYSTONE_NODES: {
    name: "Keystone Nodes",
    stakerAddress:
      "0x034641838948563bd99e84cd814314773b43f1975b4412625489b8bc368bc8fa" as Address,
    logoUrl: new URL("https://i.ibb.co/MB4KbZ1/keystone-nodes-logo.jpg"),
  },
  EJARA: {
    name: "Ejara",
    stakerAddress:
      "0x03d08c023aa3224427b6e91c8fd1b0695140b1dd5c4e69fd4e733dc6a98ea52c" as Address,
    logoUrl: new URL(
      "https://cdn.prod.website-files.com/65c39da587beed48eca7ead3/67f657686c86f47cedc4c5f9_Logo%20Horizontal.svg"
    ),
  },
  ATEMU: {
    name: "Atemu",
    stakerAddress:
      "0x01d1691876af1c5d9f96b8159f7219aa8f111712840056480184d38f6630d49e" as Address,
    logoUrl: new URL(
      "https://pbs.twimg.com/profile_images/1824381664002445314/fG3d9M84_400x400.jpg"
    ),
  },
  CITADEL_ONE: {
    name: "Citadel.one",
    stakerAddress:
      "0x0475289e9b3d5c45c4906d918451e5d32331a7bca20de3ce643f50b628f67d4d" as Address,
    logoUrl: new URL(
      "https://citadel-tx-icons.s3.eu-west-3.amazonaws.com/c1logo.png"
    ),
  },
} as const satisfies Record<string, Validator>;
